### ISSUE TITLE
Mobile view

### ISSUE THREAD

**Issue by deesclouds** [deesclouds/personal-site#3]
Mobile view is not responsive as it should be.

**Comment by abitsalihu** [comment]
@deesclouds I checked the website, I would like to help with this issue. :)

**Comment by deesclouds** [comment]
@abitsalihu Thank you! That would be awesome ☺️

I appreciate you reaching out to help with these issues. 

I need help adding some media queries to fix the view on mobile. 

I will check out the different views on Polypane.

**Comment by abitsalihu** [comment]
@abitsalihu I'll try and implement the necessary media queries tomorrow as tonight it's really late, please assign me to this issue so people know I'm working on this :)
