### ISSUE TITLE
Resume button

### ISSUE THREAD

**Issue by deesclouds** [deesclouds/personal-site#4]
Resume button appears to be too small

**Comment by abitsalihu** [comment]
@deesclouds I would also like to help with this issue. :)

**Comment by deesclouds** [comment]
@abitsalihu I've been thinking if I should have a button or if I should add the resume link within the nav. 

What do you think looks better and feels better while navigating.

**Comment by abitsalihu** [comment]
@deesclouds I think the best position would be on the right side of the nav bar, after the contact link.
